Repository Vladyslav-Team/frontend, pull requests merged in 2023-04, with the labels that each got.

#73 Bug fixed email validation#72
  src/components/pages/SignUp/validationRules.js
Labels: frontend

#93 Frontend#80 Get all info for talent on id Sign out process#69
  src/components/Header/components/ArrowButton/ArrowButton.jsx
  src/components/pages/Profile/Profile.jsx
  src/components/pages/Profile/api/index.js
  src/shared/api/services/authentication.js
  src/shared/api/services/axiosInstances.js
  src/store/index.js
Labels: frontend, task

#94 Create Delete button #65
  src/components/EditPage/EditPage.jsx
  src/components/EditPage/components/DeleteField/DeleteField.jsx
  src/components/EditPage/components/DeleteField/DeleteField.module.css
  src/components/EditPage/components/DeleteField/api/index.js
  src/components/EditPage/components/DeleteField/index.js
  src/components/EditPage/components/NameStage.jsx
  src/components/Header/Header.jsx
  src/components/pages/Profile/components/Aside/components/Biography/Biography.jsx
  src/store/index.js
Labels: frontend, task

#102 Creation of proofs with statuses and confirmations #67
  src/Theme/Theme.js
  src/components/pages/Profile/Profile.jsx
  src/components/pages/Profile/components/Aside/components/Content/Content.jsx
  src/components/pages/Profile/components/Aside/components/Content/Content.module.css
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/Proof.jsx
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/Proof.module.css
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ConfirmPopup/ConfirmPopup.jsx
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ConfirmPopup/getConfirmBody.js
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ConfirmPopup/index.js
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ProofActivity/ProofActivity.jsx
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ProofActivity/index.js
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ProofContent/ProofContent.jsx
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ProofContent/index.js
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ProofHeader/ProofHeader.jsx
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ProofHeader/index.js
  src/components/pages/Profile/components/ProfileSidebar/ProfileSidebar.module.css
Labels: frontend, task

#112 Сreated Proof editing functionality #87
  src/Router/Router.jsx
  src/components/EditProofPage/EditProofPage.jsx
  src/components/EditProofPage/index.js
  src/components/pages/Profile/Profile.module.css
  src/components/pages/Profile/components/Aside/components/Content/Content.jsx
  src/components/pages/Profile/components/Aside/components/Content/components/ContentActions/ContentActions.jsx
  src/components/pages/Profile/components/Aside/components/Content/components/ContentActions/index.js
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/Proof.jsx
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ConfirmPopup/ConfirmPopup.jsx
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ConfirmPopup/components/DialogPopup.jsx
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ConfirmPopup/components/index.js
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ConfirmPopup/getConfirmBody.js
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ProofActivity/ProofActivity.jsx
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ProofContent/ProofContent.jsx
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ProofForm/ProofForm.jsx
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ProofForm/index.js
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ProofHeader/ProofHeader.jsx
Labels: frontend, task

#125 Bug fix#1
  src/App.jsx
  src/components/EditPage/EditPage.jsx
  src/components/EditPage/components/NameStage.jsx
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/Footer/index.js
  src/components/Main/CardsList/components/TalentCard/ProofCard.jsx
  src/components/Main/CardsList/components/TalentCard/TalentCard.module.css
  src/components/Main/Main.module.css
  src/components/Proof/Proof.jsx
  src/components/SigninPopup/SigninPopup.jsx
  src/components/pages/Profile/Profile.module.css
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/Proof.jsx
  src/components/pages/Profile/components/Aside/components/Content/components/Proof/components/ProofForm/ProofForm.jsx
  src/components/pages/SignUp/validationRules.js
  src/index.css
  src/shared/api/services/axiosInstances.js
Labels: bug, frontend

#145 Fix date bug
  src/components/EditPage/EditPage.jsx
  src/components/EditPage/components/basicInfoChange/components/BirthDate.jsx
Labels: bug, frontend
